/**:
  ros__parameters:
    image_transport: raw    # image format
    family: 36h11           # tag family name
    size: 0.05              # default tag edge size in meter
    max_hamming: 0          # maximum allowed hamming distance (corrected bits)

    detector:
      threads: 1
      decimate: 2.0
      blur: 0.0
      refine: true
      sharpening: 0.25
      debug: false

    pose_estimation_method: "pnp"

    tag:
      ids: [0, 1, 2, 3, 4, 5, 6, 7]
      frames: [
        tag36h11_0,
        tag36h11_1,
        tag36h11_2,
        tag36h11_3,
        tag36h11_4,
        tag36h11_5,
        tag36h11_6,
        tag36h11_7
      ]
      sizes: [0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05, 0.05]

